apiVersion: v1
kind: ConfigMap
metadata:
  name: microapp-config
  namespace: microapp
  labels:
    app.kubernetes.io/name: microapp
data:
  POSTGRES_DB: microapp
  POSTGRES_USER: postgres
  EVOLUTION_INSTANCE_NAME: hub_escola
  CORS_ORIGINS: http://localhost,http://127.0.0.1,http://localhost:30080,http://127.0.0.1:30080
  CORS_ALLOWED_ORIGINS: http://localhost,http://127.0.0.1,http://localhost:30080,http://127.0.0.1:30080
  CORS_ALLOW_LAN: "true"
  EVOLUTION_API_URL: http://evolution:8080
  SERVER_URL: http://localhost:30808
  LANGUAGE: pt-BR
